### PR TITLE
Remove i18n function from variable

### PR DESCRIPTION
**Pull request by grappler**
Variables cannot be translated like this. The text domain would be defined in theme.

The wiki could be updated with this instead.
```php
if (class_exists('MultiPostThumbnails')) {
    new MultiPostThumbnails(
        array(
            'label' => __( 'Secondary Image', 'theme-text-domain' ),
            'id' => 'secondary-image',
            'post_type' => 'post'
        )
    );
}
```

Add text domain to plugin header as it is best practice.

### CODE REVIEW

**Comment by grappler** [comment]
I have also removed the `de_DE` translation as it was incomplete and it is not needed to be added the plugin due to language packs. The translation on https://translate.wordpress.org/projects/wp-plugins/multiple-post-thumbnails/dev/de/default is complete.

**Comment by grappler** [comment]
@chrisscott It would be great if you could merge this PR so that I can use the language packs from wp.org. Let me know if you have any questions.

**Comment by chrisscott** [comment]
Thanks @grappler ! I'm testing this out now...

**Comment by grappler** [comment]
@chrisscott Do you think you can merge these changes?

**Comment by grappler** [comment]
Closing due to no movement. Can reopen if needed.

**Pull request closed without merging**
